# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2015-12-29 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_topnames'),
    ]

    operations = [
        migrations.AddField(
            model_name='topnames',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
